# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.require_plugin "vagrant-berkshelf"
Vagrant.require_plugin "vagrant-omnibus"

Vagrant.configure("2") do |config|
  # All Vagrant configuration is done here. The most common configuration
  # options are documented and commented below. For a complete reference,
  # please see the online documentation at vagrantup.com.

  config.vm.hostname = "environment-version-tester-test"

  # Every Vagrant virtual environment requires a box to build off of.
  config.vm.box = "precise64"

  # The url from where the 'config.vm.box' box will be fetched if it
  # doesn't already exist on the user's system.
  config.vm.box_url = "http://files.vagrantup.com/#{config.vm.box}.box"
  
  config.omnibus.chef_version = "11.6.2"
  config.berkshelf.enabled = true

  config.vm.provision :chef_solo do |chef|
    
    chef.environments_path = "environments"
    chef.environment = "test"
    
    #chef.arguments = '-l debug'
      
    chef.run_list = [
        "recipe[environment-version-tester]"
    ]
  end
  
end
